version: '3'
services:

  mongodb:
    image: mongo:4
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gbdmall
    volumes:
      - egg-mongo:/data/db
      - ./init.d/mongo:/docker-entrypoint-initdb.d
    networks:
      - docker_gbdmall
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gbdmall
    networks:
      - docker_gbdmall
    ports:
      - 6379:6379

volumes:
  egg-mongo:

networks:
  docker_gbdmall:
    driver: bridge